config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/customers')

  resources :customers do
    resource :site, only: [:new, :create, :update, :destroy]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord

  ## validations ##
  validates_presence_of :company, :address, :phone_number

  ## methods ##

  def has_site?
    self.site_builder_site_id.present?
  end

  def to_site_attributes
    {
      name: self.company,
      metadata: {
        address: self.address,
        phone_number: self.phone_number,
        opening_hours: self.opening_hours,
        social_links: {
          google: self.google_plus_link,
          facebook: self.facebook_link,
          twitter: self.twitter_link
        }
      }
    }
  end

end

app/models/site.rb
class Site

  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :theme_id, :name, :email, :password, :password_confirmation

  ## validations ##
  validates_each :theme_id, :name, :email, :password, :password_confirmation do |record, attr, value|
    record.errors.add attr, "can't be blank" if value.blank?
  end

  validates :password, confirmation: true

  def attributes
    {
      theme_id: self.theme_id,
      name: self.name,
      email: self.email,
      password: self.password
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        UpdateSiteJob.perform_later(@customer.id)

        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:company, :address, :phone_number, :google_plus_link, :facebook_link, :twitter_link, opening_hours: { monday: [], tuesday: [], wednesday: [], thursday: [], friday: [], saturday: [] })
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  before_action :set_customer, only: [:new, :create, :update]

  # GET /customers/1/site/new
  def new
    @site = Site.new(name: 'John', email: 'john@doe.net', password: 'test31', password_confirmation: 'test31')
  end

  # POST /customers/1/site
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.valid?
        CreateSiteJob.perform_later(@customer.id, @site.attributes)

        format.html { redirect_to @customer, notice: 'The site is being created. Please refresh that page.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1/site
  def update
    puts "TODO CREATE UPDATE"
    redirect_to customer_path(@customer)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :email, :password, :password_confirmation, :theme_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/sites_helper.rb
module SitesHelper

  def select_options_for_themes
    $site_builder_client.themes.all.map do |theme|
      [theme.name, theme.id]
    end
  end

end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <hr/>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <hr/>

  <div class="field">
    <table>
      <tbody>
        <% ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].each do |day| %>
          <tr>
            <th><%= day %></th>
            <td>
              <%= text_field_tag "customer[opening_hours][#{day.underscore}][]", ((@customer.opening_hours || {})[day.underscore] || [])[0] || '9h00' %>
              <%= text_field_tag "customer[opening_hours][#{day.underscore}][]", ((@customer.opening_hours || {})[day.underscore] || [])[1] || '12h00' %>
              &nbsp;&mdash;&nbsp;
              <%= text_field_tag "customer[opening_hours][#{day.underscore}][]", ((@customer.opening_hours || {})[day.underscore] || [])[2] || '14h00' %>
              <%= text_field_tag "customer[opening_hours][#{day.underscore}][]", ((@customer.opening_hours || {})[day.underscore] || [])[3] || '17h00'%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <hr/>

  <div class="field">
    <%= f.label :google_plus_link %>
    <%= f.text_field :google_plus_link %>
  </div>

  <div class="field">
    <%= f.label :facebook_link %>
    <%= f.text_field :facebook_link %>
  </div>

  <div class="field">
    <%= f.label :twitter_link %>
    <%= f.text_field :twitter_link %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<% content_for :title, 'Editing Customer' %>

<div class="page-actions">
  <%= link_to 'Show', @customer, class: 'btn' %>
  &nbsp;or&nbsp;
  <%= link_to 'Back to the list', customers_path %>
</div>

<%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<% content_for :title, 'Customers' %>

<div class="page-actions">
  <%= link_to 'New Customer', new_customer_path, class: 'btn' %>
</div>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Site ?</th>
      <th>Address</th>
      <th>Phone number</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.company %></td>
        <td><%= customer.has_site? ? 'Yes' : 'no' %></td>
        <td><%= customer.address %></td>
        <td><%= customer.phone_number %></td>
        <td class="actions">
          <% unless customer.has_site? %>
            <%= link_to 'Create site', new_customer_site_path(customer), class: 'btn btn-sm' %>
          <% end %>

          <%= link_to 'Show', customer, class: 'btn btn-sm' %>
          <%= link_to 'Edit', edit_customer_path(customer), class: 'btn btn-sm' %>
          <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<% content_for :title, 'New Customer' %>

<div class="page-actions">
  <%= link_to 'Back to the list', customers_path %>
</div>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<% content_for :title, 'Show Customer' %>

<div class="page-actions">
  <% unless @customer.has_site? %>
    <%= link_to 'Create SiteBuilder site', new_customer_site_path(@customer), class: 'btn' %>
    &nbsp;or&nbsp;
  <% end %>
  <%= link_to 'Edit', edit_customer_path(@customer), class: 'btn' %>
  &nbsp;or&nbsp;
  <%= link_to 'Back to the list', customers_path %>
</div>

<p>
  <strong>Company:</strong>
  <%= @customer.company %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<div>
  <p><strong>Opening hours</strong></p>
  <ul>
    <% ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].each do |day| %>
      <li>
        <strong><%= day %></strong>
        <%= ((@customer.opening_hours || {})[day.underscore] || [])[0] || '?' %>
        -
        <%= ((@customer.opening_hours || {})[day.underscore] || [])[1] || '?' %>
        &nbsp;&mdash;&nbsp;
        <%= ((@customer.opening_hours || {})[day.underscore] || [])[2] || '?' %>
        -
        <%= ((@customer.opening_hours || {})[day.underscore] || [])[3] || '?' %>

      </li>
    <% end %>
  </ul>
<div>


<p>
  <strong>Google plus link:</strong>
  <%= @customer.google_plus_link %>
</p>

<p>
  <strong>Facebook link:</strong>
  <%= @customer.facebook_link %>
</p>

<p>
  <strong>Twitter link:</strong>
  <%= @customer.twitter_link %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locomotive SiteBuilder - Simple CRM</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navigation-app">
      <div class="nav-brand">Simple CRM</div>
      <div class="nav-title"><%= yield :title %></div>
    </div>

    <div class="container">
      <% if notice %>
        <p id="notice"><%= notice %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for site, url: customer_site_path(@customer) do |f| %>

  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :theme_id %>
    <%= f.select :theme_id, select_options_for_themes %>
  </div>

  <div class="field">
    <%= f.label :name, 'Site owner name' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>

<% end %>

app/views/sites/new.html.erb
<% content_for :title do %><%= @customer.company %> - New Site<% end %>

<div class="page-actions">
  <%= link_to 'Back to the list', customers_path %>
</div>

<%= render 'form', site: @site %>